### ISSUE TITLE
Update UI to use new taxonomies API

### ISSUE THREAD

**Issue by mirekys** [oarepo/quasar-taxonomy-editor#2]
- [x] Add paging support

- [x] Add filtering/search

- [x] Creation of taxonomy term

- [x] Term selector

- [x] Safe move operation (instead of drag&drop)

- [x] I18n

- [ ] Selector - permissions on terms (for example, do not allow selecting containers)

- [x] Build as library

- [ ] Add a readme

**Comment by mesemus** [comment]
Pull request at https://github.com/oarepo/flask-taxonomies/pull/88
